const get=(req,res)=>{
    res.send([
        {
            "id":1,
            "name":"JBL C100SI Wired ",
            "category": "accessories",
            "description":"Headphones with Mic, JBL Pure Bass Sound, One Button Multi-function Remote, Angled Buds for Comfort fit (Black) ",
            "image":"https://m.media-amazon.com/images/I/615ekapl+pL._AC_UY327_FMwebp_QL65_.jpg",
            "price":599,
            "oPrice":"₹1,299",
            "rating":"4",
            "ratingCount":"10,456",
        },  
        {
            "id":2,
            "name":" PTron Tangentbeat in-Ear Bluetooth 5.0",
            "category": "accessories",
            "description":" Wireless Headphones with Mic, Deep Bass, 10mm Drivers, Clear Calls, Snug-Fit, Fast Charging, Magnetic Buds, Voice Assistant & IPX4 Wireless Neckband",
            "image":"https://m.media-amazon.com/images/I/61rmtdRaDYL._AC_UY327_FMwebp_QL65_.jpg",
            "price":1099,
            "oPrice":"₹2,499",
            "rating":"3",
            "ratingCount":"2,745",
        },  
        {
            "id":3,
            "name":"Wecool Nylon Braided  ",
            "category": "accessories",
            "description":" Fast Charging Cable For Android Smartphone, Ios And Type C Usb Devices, 3 In 1 Charging Cable, 3A, (3 Feet) (Black)",
            "image":"https://m.media-amazon.com/images/I/71DGHA8osEL._AC_UY327_FMwebp_QL65_.jpg",
            "price":549,
            "oPrice":"₹999",
            "rating":"5",
            "ratingCount":"27",
        }, 
        {
            "id":4,
            "name":"Apple Adapter ",
            "category": "accessories",
            "description":" 20W USB-C Power Adapter (for iPhone, iPad & AirPods) ",
            "image":"https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/61vtLhO6fDL._SY741_.jpg",
            "price":1550,
            "oPrice":"₹1,990",
            "rating":"5",
            "ratingCount":"20,684",
        },  
        {
            "id":5,
            "name":" CableCreation USB C to 3.5mm Headphone",
            "description":" Audio Adapter 2-in-1 USB C Type-C to Hi-Res 3.5mm Audio with PD Fast Charging Adapter, Compatible with OnePlus Nord 2T/10 Pro,Pixel 2/2XL/3/3XL, Aluminum",
            "image":"https://m.media-amazon.com/images/I/31wIjNqXhSL._AC_UY327_FMwebp_QL65_.jpg",
            "price":1550,
            "oPrice":"₹1,700",
            "rating":"4",
            "ratingCount":"589",
        },  
        {
            "id":6,
            "name":"SanDisk Ultra® ",
            "category": "accessories",
            "description":"microSDXC™ UHS-I Card, 256GB, 150MB/s R, 10 Y Warranty, for Smartphones ",
            "image":"https://m.media-amazon.com/images/I/81i8riahalS._AC_UY327_FMwebp_QL65_.jpg",
            "price":1550,
            "oPrice":"₹3,500",
            "rating":"5",
            "ratingCount":"67,890",
        },
        {
            "id": 7,
            "name": "iPad Pro M1 ",
            "category": "ipad",
            "image": "https://m.media-amazon.com/images/I/81a-rN2A3DS._SX679_.jpg",
            "price": 175900,
            "oPrice": "₹184900"
        },
        {
            "id":8,
            "name":"Apple 2022  iPad ",
            "category": "ipad",
            "image":"https://m.media-amazon.com/images/I/71VbHaAqbML._AC_UY327_FMwebp_QL65_.jpg",
            "price":126999,
            "oPrice":"₹1,27,999",
        },  
        {
            "id":9,
            "name":"Samsung Galaxy Tab ",
            "category": "ipad",
            "image":"https://m.media-amazon.com/images/I/51rrWvzviVL._AC_UY327_FMwebp_QL65_.jpg",
            "price":15000,
            "oPrice":"₹21,599",
        },   
        {
            "id":10,
            "name":"Xiaomi Pad 5 ",
            "category": "ipad",
            "image":"https://m.media-amazon.com/images/I/61Eb9vtdSML._AC_UY327_FMwebp_QL65_.jpg",
            "price":26999,
            "oPrice":"₹37,999",
        },   
        {
            "id":11,
            "name":"IKALL N7 WiFi Only Tablet ",
            "category": "ipad",
            "description":"7 Inch IPS Display, Android 6.0| 2GB RAM, 16GB Storage -Black",
            "image":"https://m.media-amazon.com/images/I/51djfwRq5bS._AC_UL480_FMwebp_QL65_.jpg",
            "price":4999,
            "oPrice":"₹5,999",
            "rating":"3",
            "ratingCount":"87",
        },   
        {
            "id":12,
            "name":"realme Pad X WiFi+5G Tablet ",
            "category": "ipad",
            "description":"6GB RAM 128GB ROM (Expandable), 27.9cm (11 inch) WUXGA+ Display | 6nm SD Processor | Dolby Atmos Quad Speakers | 8340 mAh Battery ",
            "image":"https://m.media-amazon.com/images/I/614ofbAkWxL._AC_UY327_FMwebp_QL65_.jpg",
            "price":26999,
            "oPrice":"₹44,999",
            "rating":"3",
            "ratingCount":"5,667",
        }, 
        {
            "id": 13,
            "name": "Apple iPhone 14 Pro Max (128 GB)",
            "category": "Mobile",
            "image": "https://m.media-amazon.com/images/I/71yzJoE7WlL._SX342_.jpg",
            "price": 127999,
            "oPrice": "₹1,39,900"
        },
        {
            "id": 14,
            "name": "Apple iPhone 14 (512 GB) ",
            "category": "Mobile",
            "image": "https://m.media-amazon.com/images/I/61bK6PMOC3L._SX342_.jpg",
            "price": 101999,
            "oPrice": "₹1,09,900"
        },
        {
            "id": 15,
            "name": "iPhone 14 Plus (256 GB)",
            "category": "Mobile",
            "image": "https://m.media-amazon.com/images/I/71emcsxsRPL._SX679_.jpg",
            "price": 100304,
            "oPrice": "₹1,10,304"

        },
        {
            "id": 16,
            "name": "OnePlus 10 R",
            "category": "Mobile",
            "image": "https://m.media-amazon.com/images/I/716uVx3Wr5L._AC_SS450_.jpg",
            "price": 35000,
            "oPrice": "₹38,499"

        },
    ])
}

module.exports.apiController = get